[General]
# 候補ウィンドウの項目数
PageSize=10
# 候補リストのレイアウト
CandidateLayout=Vertical
# 候補を表示するまでの変換キーの押し下げ回数
NTriggersToShowCandWin=2
# 入力を予測する
PredictOnInput=False
# 空白のキーで空白を挿入します
RomajiPseudoAsciiBlankBehavior=True
# 大文字で疑似ASCII入力モードに入る
RomajiPseudoAsciiMode=True
# シンボルには半角文字を使用する
RomajiHalfSymbol=True
# 数字には半角文字を使用する
RomajiHalfNumber=True
# 初期入力モード
InputMode=Hiragana
# 入力方式
TypingMethod=Romaji
# 変換モード
ConversionMode="Multi segment"
# 句読点のスタイル
PeriodStyle=Japanese
# 記号のスタイル
SymbolStyle=Japanese
# スペースタイプ
SpaceType="Follow mode"
# テンキータイプ
TenKeyType="Follow mode"
# カンマやピリオドの動作
PeriodBehavior=None
# 手動学習
LearnOnManualCommit=True
# 自動学習
LearnOnAutoCommit=True
# 分割を許可
AllowSplit=True
# 予測中に直接選択キーを使用する
UseDirectKeyOnPredict=True
# 候補のラベルを表示
ShowCandidatesLabel=True

[Interface]
# 入力モードを表示
ShowInputMode=True
# 入力方式を表示
ShowTypingMethod=True
# 変換モードを表示
ShowConversionMode=True
# 句読点のスタイルを表示
ShowPeriodStyle=False
# 記号のスタイルを表示
ShowSymbolStyle=False

[KeyProfile]
# キーバインドのプロファイル
KeyBindingProfile=Default
# ローマ字配列
RomajiTable=Default
# カナ配列
KanaTable=Default
# Nicola配列
NicolaTable=Default
# 独自のキーバインド
CustomKeyBinding=
# 独自のローマ字配列
CustomRomajiTable=
# 独自のかな配列
CustomKanaTable=
# 独自のNicola配列
CustomNicolaTable=

[Key]
# 英数とかなモード循環
CircleLatinHiraganaModeKey=
# 英数モード
LatinModeKey=
# 全角英字モ－ド
WideLatinModeKey=
# ひらがなモード
HiraganaModeKey=
# カタカナモード
KatakanaModeKey=
# 半角カタカナモード
HalfKatakanaModeKey=
# 半角スペースの挿入
InsertHalfSpaceKey=
# 全角スペースの挿入
InsertWideSpaceKey=
# 全てキャンセル
CancelAllKey=
# 再変換した最初の文節を確定
CommitFirstSegmentReverseLearnKey=
# 再変換した選択済み文節を確定
CommitSelectedSegmentReverseLearnKey=
# 前の文字種に変換
ConvertCharTypeBackwardKey=
# かなレイアウト用の「ろ」キー
KanaLayoutRoKey=ろ
# Nicola時間
NicolaTime=200

[Key/CircleInputModeKey]
0=Control+comma
1=Control+less

[Key/CircleKanaModeKey]
0=Control+period
1=Hiragana_Katakana

[Key/CircleTypingMethodKey]
0=Alt+Romaji
1=Control+slash

[Key/CancelPseudoAsciiModeKey]
0=Escape

[Key/InsertSpaceKey]
0=space

[Key/InsertAltSpaceKey]
0=Shift+space

[Key/BackSpaceKey]
0=BackSpace
1=Control+H

[Key/DeleteKey]
0=Delete
1=Control+D

[Key/CommitKey]
0=Return
1=KP_Enter
2=Control+J

[Key/CommitReverseLearnKey]
0=Shift+Return

[Key/ConvertKey]
0=space
1=KP_Space
2=Henkan
3=Down

[Key/PredictKey]
0=Tab

[Key/CancelKey]
0=Escape
1=Control+G

[Key/MoveCaretFirstKey]
0=Control+A
1=Home

[Key/MoveCaretLastKey]
0=Control+E
1=End

[Key/MoveCaretForwardKey]
0=Control+F
1=Right

[Key/MoveCaretBackwardKey]
0=Control+B
1=Left

[Key/SelectFirstSegmentKey]
0=Control+A
1=Home

[Key/SelectLastSegmentKey]
0=Control+E
1=End

[Key/SelectNextSegmentKey]
0=Control+F
1=Right

[Key/SelectPrevSegmentKey]
0=Control+B
1=Left

[Key/ShrinkSegmentKey]
0=Shift+Left
1=Control+I

[Key/ExpandSegmentKey]
0=Shift+Right
1=Control+O

[Key/CommitFirstSegmentKey]
0=Shift+Down

[Key/CommitSelectedSegmentKey]
0=Control+Down

[Key/SelectFirstCandidateKey]
0=Home

[Key/SelectLastCandidateKey]
0=End

[Key/SelectNextCandidateKey]
0=space
1=Tab
2=Henkan
3=Down
4=KP_Space

[Key/SelectPrevCandidateKey]
0=Shift+Tab
1=Up

[Key/CandidatesPageUpKey]
0=Page_Up

[Key/CandidatesPageDownKey]
0=Next

[Key/ConvertCharTypeForwardKey]
0=Muhenkan

[Key/ConvertToHiraganaKey]
0=F6

[Key/ConvertToKatakanaKey]
0=F7

[Key/ConvertToHalfKey]
0=F8

[Key/ConvertToHalfKatakanaKey]
0=Shift+F8

[Key/ConvertToWideLatinKey]
0=F9

[Key/ConvertToLatinKey]
0=F10

[Key/ReconvertKey]
0=Shift+Henkan

[Key/DictAdminKey]
0=F11

[Key/AddWordKey]
0=F12

[Key/LeftThumbKey]
0=Muhenkan

[Key/RightThumbKey]
0=Henkan
1=space

[Command]
# 単語の追加
AddWord="kasumi -a"
# 辞書の編集
DictAdmin=kasumi

